/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Law = IDL.Record({
  'title' : IDL.Text,
  'explanation' : IDL.Text,
  'number' : IDL.Nat,
});
export const Preamble = IDL.Record({
  'title' : IDL.Text,
  'explanation' : IDL.Text,
});

export const idlService = IDL.Service({
  'addLaw' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'clear' : IDL.Func([], [], []),
  'getAllLaws' : IDL.Func([], [IDL.Vec(Law)], ['query']),
  'getLaw' : IDL.Func([IDL.Nat], [IDL.Opt(Law)], ['query']),
  'getPreamble' : IDL.Func([], [IDL.Opt(Preamble)], ['query']),
  'initializeLaws' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Text))],
      [],
      [],
    ),
  'setPreamble' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Law = IDL.Record({
    'title' : IDL.Text,
    'explanation' : IDL.Text,
    'number' : IDL.Nat,
  });
  const Preamble = IDL.Record({ 'title' : IDL.Text, 'explanation' : IDL.Text });
  
  return IDL.Service({
    'addLaw' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'clear' : IDL.Func([], [], []),
    'getAllLaws' : IDL.Func([], [IDL.Vec(Law)], ['query']),
    'getLaw' : IDL.Func([IDL.Nat], [IDL.Opt(Law)], ['query']),
    'getPreamble' : IDL.Func([], [IDL.Opt(Preamble)], ['query']),
    'initializeLaws' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Text))],
        [],
        [],
      ),
    'setPreamble' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };